mysql:
  host: localhost
  port: 3306
  database: dev
  user: eclipse
  password: maggots
  schema-version: 0
strings:
  no-permissions: '&cYou don''t have permission to do that!'
  not-enough-args: '&cNot enough arguments!'
  lookup-uuid-command-usage: |
    '&6/lookup uuid &b[ip]&9 - &aGet a list of ips that have been used by a uuid
    '&6/lookup uuid &b[name]&9 - &aGet a list of names that have been used by a uuid
  uuids-from-ip-result-header: '&6UUIDS that have used the ip &b%ip%&6:'
  uuids-from-ip-result: '&f[%#%] &6%uuid%'