CREATE TABLE IF NOT EXISTS pl_names (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `player_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  FOREIGN KEY (`player_id`) REFERENCES pl_uuids(`id`)
    ON UPDATE CASCADE
	ON DELETE CASCADE
) ENGINE=InnoDB;